sudo: false
language: node_js
node_js:
  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'npm test'
  - 'grunt build'
after_success:
  - 'grunt nugetpush'
