sudo: false
language: node_js
node_js:
  - '0.12'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
